jupyterhub:
  hub:
    nodeSelector:
      cloud.google.com/gke-nodepool: core-pool
    baseUrl: /nbgrader-hub/
    annotations:
      prometheus.io/scrape: "true"
      # this needs to start with the value of `hub.baseUrl`
      prometheus.io/path: /nbgrader-hub/hub/metrics
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 256Mi
  singleuser:
    image:
      # tag will be set by travis on deployment
      name: earthlabhubops/ea-k8s-user-nbgrader-hub
      tag: set-on-deployment
    startTimeout: 600
    cpu:
      guarantee: 0.1
      limit: 1.
    memory:
      guarantee: 500M
      limit: 500M
  proxy:
    nodeSelector:
      cloud.google.com/gke-nodepool: core-pool
    service:
      type: ClusterIP
    chp:
      resources:
        requests:
          cpu: 200m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 128Mi
  ingress:
    enabled: true
    hosts:
      - hub.earthdatascience.org
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    tls:
      - secretName: kubelego-tls-jupyterhub
        hosts:
          - hub.earthdatascience.org

  auth:
    type: github
    admin:
      access: true
      users:
        - kcranston
        - lwasser
    whitelist:
      users:
        - earth-lab
        - kcranston
        - lwasser
        - jlpalomino
        - nkorinek
        - wino6687
        - mbjoseph
        - lherwehe
    github:
      callbackUrl: "https://hub.earthdatascience.org/nbgrader-hub/hub/oauth_callback"
